### ISSUE TITLE
Import failed, path does not exist or is not accessible by Radarr

### ISSUE THREAD

**Issue by j-burton** [mdhiggins/radarr-sma#10]
First off, this is my first time to play with Docker.
I believe I followed the instructions on how to set up docker with radarr, made a fresh install of nzbget with no options set apart from my usenet server.
In radarr I have Nzbget as the download client and completed download handling enabled. In the connections, /usr/local/sma/postRadarr.sh is setup

The download handles fine but as soon as its downloaded, nothing happens, the file is left in the download directory, not renamed.

this is from the radarr log:

Import failed, path does not exist or is not accessible by Radarr: /volume1/downloads/completed/Movies/Casablanca.1942.70th.Anniversary.1080p.BluRay.DTS-HD.MA.1.0.x264-HDH

![Screenshot (5)](https://user-images.githubusercontent.com/4857963/79446426-dc183100-7fe6-11ea-9155-698278d41501.png)

![Screenshot (9)](https://user-images.githubusercontent.com/4857963/79446933-c0615a80-7fe7-11ea-8e91-2780a134f386.png)
![Screenshot (10)](https://user-images.githubusercontent.com/4857963/79446943-c3f4e180-7fe7-11ea-8732-1f83e1e0befd.png)
![Screenshot (11)](https://user-images.githubusercontent.com/4857963/79446953-c6efd200-7fe7-11ea-8d51-2be8ddd466a3.png)

**Comment by mdhiggins** [comment]
Seems like you need to make sure your paths are consistent across your containers. The path to your downloads seems to be in /downloads in Radarr and /volume1/downloads in NZBGet

**Comment by j-burton** [comment]
Are you suggesting I use nzbget in a docker also?

**Comment by mdhiggins** [comment]
Yep, if you’re gonna use docker you might as well use it for the whole setup. Otherwise you’ll have issues and there’s no point. At least for the integrated components.

**Comment by j-burton** [comment]
I'll give it a go now...

**Comment by j-burton** [comment]
Working fantastically, youre the best

Can you shed any light on why my Plex isnt updating after each download?

[Plex]
host = 192.168.1.100
port = 32400
refresh = True
token = j5JiWfx5LFsEU6qa6CCm


I cant find anything at all in the logs

**Comment by mdhiggins** [comment]
That should be fine unless the token is expired. The logs should shed some light onto why it’s failing. If plex is in a docker container some network setups can have issues.
