### ISSUE TITLE
manual.py script not working in container

### ISSUE THREAD

**Issue by automator0** [mdhiggins/radarr-sma#11]
In the latest container, the manual.py script is not working due to a guessit error

Traceback (most recent call last):
  File "./manual.py", line 5, in <module>
    import guessit
ModuleNotFoundError: No module named 'guessit'

Is something missing?

**Comment by mdhiggins** [comment]
Are you executing the script in the correct virtual environment? For the container all the dependencies are installed using venv and you need to execute within that environment

`/usr/local/sma/venv/bin/python3 /usr/local/sma/manual.py`

**Comment by automator0** [comment]
That was it! Noted it is in the other environment

Thanks!
