### ISSUE TITLE
update to "nightly" instead of "preview" for radar image

### ISSUE THREAD

**Issue by powerdude** [mdhiggins/radarr-sma#13]
hi,

it seems the `preview` tag for `linuxserver/radarr` has been replaced with `nightly`.  any plans to update this image to use `nightly`?

**Comment by mdhiggins** [comment]
Wasn't aware they had made this change

Just pushed updates, give docker hub some time to update the builds

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/radarr-sma/tree/nightly
