### ISSUE TITLE
Frage zum Thema FFmpeg Vaapi ( Nginx-RTMP)

### ISSUE THREAD

**Issue by ghost** [mdhiggins/radarr-sma#17]
Abend

hätte mal ne frage wäre es möglich auch nach Twitch zu streamen mit Nginx und RTMP?
Wenn ja hatten sie das mal getestet?

Viele Grüße

**Comment by mdhiggins** [comment]
I have no idea and I don't think this script has anything to do with twitch

Had to run this through google translate so hope I understood correctly

**Comment by mdhiggins** [comment]
Also don't think this anything do with Radarr either?

**Comment by mdhiggins** [comment]
Feel free to continue discussion or reopen if I am incorrect in my understanding
