### ISSUE TITLE
mp4 not created

### ISSUE THREAD

**Issue by hoyane** [mdhiggins/radarr-sma#23]
Hello, my conversions in radarr will not finish. Right when it finishes it throws an error and does not create the mp4. I cant see any real useful information in the log file even with debug on. I know this is a ffmpeg error but hoping you might have some insight. I even tried using the same ini from sonarr which works fine. They both use the same directories and are both updated and both use the same docker config.

LOG: https://pastebin.com/raw/vPaf1JW0
CONFIG: https://pastebin.com/raw/hRr5e32Y

**Comment by mdhiggins** [comment]
I would take the generated FFMpeg command and run it manually and see if that gives you any more info cause the logs aren't super helpful here
