### ISSUE TITLE
Unable to update Radarr directly, update the docker container to receive the update

### ISSUE THREAD

**Issue by morganzero** [mdhiggins/radarr-sma#24]
Hi, using the `:nightly` tag gives me this every time.
![bild](https://user-images.githubusercontent.com/57449785/113842451-f7012980-9792-11eb-989b-0061f1320e04.png)

**Comment by mdhiggins** [comment]
I don't understand what the issue is here

**Comment by barocko-works** [comment]
I just started to use this container. And the linuxserver nightly version looks slightly different, where it shows green if I'm up to date, and it doesn't have that exclamation mark. I think I just got worried over nothing :)

**Comment by mdhiggins** [comment]
The container doesn't rebuild nightly due to issues with overload the FFMpeg server so it might be a little behind but shouldn't be an issue. Just build the container

**Comment by barocko-works** [comment]
Excuse my ignorance but may I ask? Does *Arr firstly import/upload the file to the location and encode/convert it in that location? Or does it convert/encode it before it imports it?

**Comment by mdhiggins** [comment]
After import

**Comment by barocko-works** [comment]
Is there something I can do for the script to fire off before It imports? I rather have it encoded pre-import for multiple reasons.

**Comment by mdhiggins** [comment]
Yep see the readme
You have to configure post-downloader scripts (nzget, sab, etc) which will do the conversion before it's passed back to *arr

You'll need to set up SMA or find a container with it preinstalled though for those docker containers, the default 2 sma containers I maintain only have postSoanrr/postRadarr support. There are a few out there

**Comment by barocko-works** [comment]
I've been using sabs for over a year with good results, I started using radarr-sma just a couple of days ago, and I like the idea, especially of enjoying both Usenet and torrent conversions through one platform. Doing the post-downloader script just pushes me back to square one I guess ;D

How about I ask you this then. I currently have my config for radarr/sonarr-sma setup like this. Would you be kind and review it for me. What I'm trying to achieve is the following:

I want it to convert the media to MKV, even if the extension already is MKV. I want it to contain h264/x264 video format with AAC, both 2ch and 6ch audio, and keep the original audio source as well. Embed SRT or ASS subtitles as well as image subs like PGS. And if the original file already included (`bypass-if-copying-all = True`) what I just wrote I want it to bypass (`process-same-extensions = True`)

my autoProcess.ini
``` [Converter]
ffmpeg = /usr/local/bin/ffmpeg
ffprobe = /usr/local/bin/ffprobe
threads = 0
hwaccels = 
hwaccel-decoders = h264_cuvid, mjpeg_cuvid, mpeg1_cuvid, mpeg2_cuvid, mpeg4_cuvid, vc1_cuvid, hevc_qsv$
hwdevices = vaapi:/dev/dri/renderD128
hwaccel-output-format = vaapi:vaapi
output-directory = 
output-format = mkv
output-extension = mkv
temp-extension = 
minimum-size = 0
ignored-extensions = nfo, ds_store, txt
copy-to = 
move-to = 
delete-original = True
sort-streams = True
process-same-extensions = True
bypass-if-copying-all = True
force-convert = False
post-process = False
wait-post-process = False
detailed-progress = False
opts-separator = ,
preopts = 
postopts = 
regex-directory-replace = [^\w\-_\. ]

[Permissions]
chmod = 0777
uid = 1000
gid = 1000

[Metadata]
relocate-moov = False
full-path-guess = True
tag = False
tag-language = eng
download-artwork = False
sanitize-disposition = 
strip-metadata = True

[Video]
codec = h264, x264
max-bitrate = 0
bitrate-ratio = 
crf = -1
crf-profiles = 
preset = 
codec-parameters = 
dynamic-parameters = False
max-width = 0
profile = 
max-level = 0.0
pix-fmt = 
filter = 
force-filter = False

[HDR]
codec = 
pix-fmt = 
space = bt2020nc
transfer = smpte2084
primaries = bt2020
preset = 
codec-parameters = 
filter = 
force-filter = False
profile = 

[Audio]
codec = aac
languages = 
default-language = 
first-stream-of-language = False
allow-language-relax = True
channel-bitrate = 0
max-bitrate = 0
max-channels = 0
prefer-more-channels = True
default-more-channels = True
filter = 
force-filter = False
sample-rates = 
copy-original = True
aac-adtstoasc = False
ignore-truehd = mp4, m4v
ignored-dispositions = 
unique-dispositions = False

[Universal Audio]
codec = aac
channel-bitrate = 0
first-stream-only = False
move-after = False
filter = 
force-filter = False

[Audio.ChannelFilters]
6-2 = pan=stereo|FL=0.5*FC+0.707*FL+0.707*BL+0.5*LFE|FR=0.5*FC+0.707*FR+0.707*BR+0.5*LFE

[Subtitle]
codec = srt, ass
codec-image-based = pgs
languages = 
default-language = 
first-stream-of-language = False
encoding = 
burn-subtitles = False
burn-dispositions = 
embed-subs = True
embed-image-subs = True
embed-only-internal-subs = False
filename-dispositions = forced
ignore-embedded-subs = False
ignored-dispositions = 
unique-dispositions = False
attachment-codec = ```

**Comment by mdhiggins** [comment]
Seems like what you have here should work. You'll likely end up with 3 channels for each audio stream though (aac stereo, aac multichannel, original) for any stream over 2 channels that's not already AAC

Also be cautious with this workflow that you don't process the same file multiple times, you may end up duplicating audio streams with each conversion

**Comment by barocko-works** [comment]
Thanks for your review. Yeah, I'm aware of the truplicate stream. I rather have `process-same-extensions = False` but then it would bypass all of it even if the audio source isn't AAC like I want it. I wish there was a way of telling it to process even if the audio stream doesn't match my "criteria" instead.

**Comment by barocko-works** [comment]
Btw. What do these mean?
```
post-process = False
wait-post-process = False
```

EDIT:
I obviously have read these
![bild](https://user-images.githubusercontent.com/57449785/114001116-ec5e9700-985b-11eb-9c17-bdf5223fc951.png)
In my case, I'm already using this script for post-processing. Would I benefit from settings these two parameters to `True`, is what I mean?

**Comment by mdhiggins** [comment]
You can add on additional post processing python scripts into this SMA script suite to be run afterward

https://github.com/mdhiggins/sickbeard_mp4_automator#post-process-scripts

These settings apply to this feature

**Comment by barocko-works** [comment]
Thank you so much for your time explaining and guiding @mdhiggins. I appreciate your work! ⭐

**Comment by mdhiggins** [comment]
No prob
I'm working on a https://github.com/linuxserver/docker-mods version of the SMA script so you might be able to integrate it into downloaders more easily

**Comment by barocko-works** [comment]
I'm looking forward to that 😃 👍

**Comment by mdhiggins** [comment]
Early version is published and working in my prelim tests, still need to write up the documentation but try adding this to your environment variables on a linuxserver based container, should install sma and ffmpeg, and you'll need to add a volume for your config folder just like the radarr-sma/sonarr-sma containers

`DOCKER_MODS=mdhiggins/sma-mod:latest`

https://hub.docker.com/repository/docker/mdhiggins/sma-mod

**Comment by barocko-works** [comment]
Awesome! Looking forward to it. I'll give it a test run in a few hours when it's morning.

**Comment by barocko-works** [comment]
> `DOCKER_MODS=mdhiggins/sma-mod:latest`

So I don't really need to deploy sma-mod? I just put it in env?

**Comment by mdhiggins** [comment]
Correct, only for linxuserver containers though

**Comment by barocko-works** [comment]
> Correct, only for linxuserver containers though

Great! My first move will be to deploy it within linuxserver/deluge, a client I never really got working before :)

**Comment by mdhiggins** [comment]
That was the container I had done my testing on and it seems to be working nicely

**Comment by barocko-works** [comment]
> That was the container I had done my testing on and it seems to be working nicely

@mdhiggins May I ask how you setup Deluge to perform the post process after torrent completion?

I'm looking for a way to keep seeding the original torrent. Any suggestions?

**Comment by mdhiggins** [comment]
This is covered in the readme and sma-mod includes a delugePostProcess.sh that includes all the relative path information (instead of called delugePostProcess.py directly)

It automatically makes a copy and does not modify the original torrent files so that you can keep seeding. You'll need to remove the originals from deluge at some point on your own

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/sickbeard_mp4_automator#deluge-daemon-setup

**Comment by barocko-works** [comment]
> https://github.com/mdhiggins/sickbeard_mp4_automator#deluge-daemon-setup

Thanks! Does it work well with extractor enabled?

**Comment by mdhiggins** [comment]
Nope, you'd have to modify whatever extractor script you're using to call things

**Comment by barocko-works** [comment]
> Nope, you'd have to modify whatever extractor script you're using to call things

Gotcha! May I ask which extractor you use? :)

**Comment by barocko-works** [comment]
Do you think I can do something like this?
![bild](https://user-images.githubusercontent.com/57449785/114516701-f3135280-9c3d-11eb-94ee-bbcb5a53deb4.png)

**Comment by mdhiggins** [comment]
Nope, the way delugePostProcess works is that it queries the API for a list of files to process which will no longer be accurate after you have extracted

You can set forcepath to bypass this but you'll need to call with the correct parameters
https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1181#issuecomment-599158502

**Comment by barocko-works** [comment]
> Nope, the way delugePostProcess works is that it queries the API for a list of files to process which will no longer be accurate after you have extracted
> 
> You can set forcepath to bypass this but you'll need to call with the correct parameters
> [mdhiggins/sickbeard_mp4_automator#1181 (comment)](https://github.com/mdhiggins/sickbeard_mp4_automator/issues/1181#issuecomment-599158502)

I'm giving up on Deluge. Haven't gotten it to work for the past year, I really got my hopes up now lol. Does this script you pointed me to apply to qbittorrent as well?

**Comment by mdhiggins** [comment]
https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/qBittorrent-Unrar-Script

That should generally work for qbt with only minor modifications for the python path for the docker container

**Comment by barocko-works** [comment]
> https://github.com/mdhiggins/sickbeard_mp4_automator/wiki/qBittorrent-Unrar-Script
> 
> That should generally work for qbt with only minor modifications for the python path for the docker container

Thanks. I give up. I don't know what I'm doing wrong but I don't seem to be able to get any client to work with your mod. And it's most likely my lack of skills and nothing wrong with your mod. Thanks for all your help though, I truly appreciate it!

**Comment by mdhiggins** [comment]
If you can provide some information about how its failing I can perhaps help you fix it

**Comment by barocko-works** [comment]
> If you can provide some information about how its failing I can perhaps help you fix it

Sorry to waste your time. I can't provide you any information, cause there are nothing in logs. The script doesn't execute.
