### ISSUE TITLE
nightly is wrong radarr version

### ISSUE THREAD

**Issue by player666au** [mdhiggins/radarr-sma#26]
Hi,

The nightly radarr version is showing as 3.0.2.4552.

The interface is broken in places because radarr nightly is up to 3.1.something.

Can you please have a look to see where things have gone wrong?

Thanks

**Comment by mdhiggins** [comment]
Fixed, the latest update's scheduled build was missing the `ref` in the workflow and was using the dockerfile from the stable branch, should be all set now

**Comment by player666au** [comment]
Thank you! Much appreciated
