### ISSUE TITLE
Feature request: build branch/tag added to GHCR &/or updated at Docker Hub

### ISSUE THREAD

**Issue by KaHooli** [mdhiggins/radarr-sma#28]
Can the build branch/tag please be added to [GitHub Container Registry](https://ghcr.io/mdhiggins/mdhiggins/radarr-sma) or updated on [Docker Hub](https://hub.docker.com/r/mdhiggins/radarr-sma) ?

It appears that the build tag version at Docker Hub hasn't been updated since February 2021.

Similar request with Radarr-SMA raised as well, see https://github.com/mdhiggins/sonarr-sma/issues/26

**Comment by mdhiggins** [comment]
So there really is no need since the build dockerfile is meant to be built locally, not pulled with premade images. The build arguments aren't applied if you do it this way rendering it kind of useless, it has no autobuild configuration as a result
