### ISSUE TITLE
Latest FFMPEG

### ISSUE THREAD

**Issue by automator0** [mdhiggins/radarr-sma#32]
Looks like the version of FFMPEG in the SMA container is 4.1.6.

I see there is a build tag, but how can we get this updated to the latest FFMPEG release?

I'm using the "latest" build as well

**Comment by automator0** [comment]
Please disregard, it is the latest version. Need to remove the truedhd-ignore settings

**Comment by mdhiggins** [comment]
Just in case others stumble upon this issue

You can specify an alternate URL for your FFMPEG binaries
By default you can see in the dockerfile I use

```
ENV SMA_FFMPEG_URL https://johnvansickle.com/ffmpeg/releases/ffmpeg-release-amd64-static.tar.xz
```

You can override this variable and use a different source of your choosing, but more regular builds can be found here

https://www.johnvansickle.com/ffmpeg/

Additionally you can use the `build` tag and set your ARG `ffmpeg_tag` to build your own version of FFMPEG from source using any of the versions available on https://github.com/jrottenberg/ffmpeg
