### ISSUE TITLE
Cannot run ./manual.py

### ISSUE THREAD

**Issue by niallobr** [mdhiggins/radarr-sma#36]
Hi, 

I've seen some similar issues on this like #11 but I don't seem to have any problem with Guessit or other modules. Using the latest version and latest SMA.

Here's whats happening:

Running from inside container
```
root@e1f361d58140:/# /usr/local/sma/venv/bin/python3 /usr/local/sma/manual.py

/usr/local/sma/venv/bin/python3: can't open file '/usr/local/sma/manual.py': [Errno 2] No such file or directory

root@e1f361d58140:/usr/local/sma# ls
config  postRadarr.sh  update.py  venv
```

Running from host
```
root@Apollo:~# docker exec -it radarr /usr/local/sma/venv/bin/python3 /usr/local/sma/manual.py

/usr/local/sma/venv/bin/python3: can't open file '/usr/local/sma/manual.py': [Errno 2] No such file or directory
```

Is there a reason manual.py is missing or is something else wrong?

**Comment by niallobr** [comment]
Think I figured this out so closing.

Radarr was launching fine so everything seemed normal but when I checked the Docker logs for the container there was an error during SMA setup. It seemed to be caused by some legacy/cached files in the SMA config folder on the host. Once I deleted those it pulled the new SMA files correctly.

**Comment by niallobr** [comment]
Think I figured this out so closing.

Radarr was launching fine so everything seemed normal but when I checked the Docker logs for the container there was an error during SMA setup. It seemed to be caused by some legacy/cached files like '__init__.py' in the SMA config folder on the host. Once I deleted those it pulled the new SMA files correctly.

**Comment by mdhiggins** [comment]
I'm guessing you're using the "build" tag but I believe this was a bug introduced by attempts to make the build tag compatible with alpine and ubuntu (universal essentially)

Should be fixed now
