### ISSUE TITLE
Unable to add script within radarr

### ISSUE THREAD

**Issue by djrarky** [mdhiggins/radarr-sma#37]
When adding postRadarr within Radarr, I get teh following error: 
`Script exited with code: 1`
Meaning the script won't save. 

![image](https://user-images.githubusercontent.com/10834935/168269998-107771cb-b0e8-4c8d-8d6b-566b1a4e2d25.png)

**Comment by mdhiggins** [comment]
Test is failing. Probably an import error

You install all the dependencies?

Does manual.py launch?

What error shows up in the Radarr logs?

**Comment by mdhiggins** [comment]
Actually just noticed this was the docker container and not the main SMA repo

So I know dependencies are fine cause docker handles it

You just put the wrong path, gotta read more carefully

Use `/usr/local/sma/postRadarr.sh` not `.py`
