### ISSUE TITLE
/usr/local/bin/ffmpeg missing from mdhiggins/radarr-sma:latest

### ISSUE THREAD

**Issue by player666au** [mdhiggins/radarr-sma#44]
the ffmpeg binary is not in the container.made from mdhiggins/radarr-sma:latest

root@ec11e8445a05:/# ls -la /usr/local/bin/
total 12
drwxr-xr-x 2 root root 4096 Jan 17 17:31 .
drwxr-xr-x 1 root root 4096 Feb  5 16:13 ..
root@ec11e8445a05:/#

**Comment by mdhiggins** [comment]
Are you using the SMA_USE_REPO option by chance? if so the repo defaults to /usr/bin/ffmpeg

**Comment by player666au** [comment]
ffmpeg is not there either:
root@ec11e8445a05:/# ls /usr/bin/ffmpeg
ls: cannot access '/usr/bin/ffmpeg': No such file or directory

As far as I'm aware I am using the simplest docker container.
But I am using a script for custom re-encoding which references ffmpeg, which has been working for a very long time, so the missing binary really stood out.

**Comment by mdhiggins** [comment]
You can try `which ffmpeg` to see if its installed anywhere

When did you last pull the container? There was a small window from Jan 17 to about Jan 25 where linuxserver migrated the parent container to s6v3 and the startup script that installs ffmpeg wasn't working. Try a fresh pull if you think your image might be from that timeframe

If that doesn't fix it, please post your docker logs for the container starting to see if the startup script that handles downloading ffmpeg is throwing some kind of error

**Comment by player666au** [comment]
All good!
A new container was just pulled and the ffmpeg binary is there at /usr/local/bin/ffmpeg
Thanks for looking into this so quickly.

**Comment by mdhiggins** [comment]
No prob, easy fix
