### ISSUE TITLE
ffmpeg not installing

### ISSUE THREAD

**Issue by player666au** [mdhiggins/radarr-sma#47]
https://github.com/mdhiggins/radarr-sma/blob/f26c11ba1f96e9290a76a2b196ad1ef3174621ae/root/etc/s6-overlay/s6-rc.d/init-sma-config/run#L104

Hi, the line above is returning true so that the following ffmpeg download block does not execute.

I commented this out in the container and ffmpeg was then available and my script executed

Before, 'which ffmpeg' returned nothing.
After, 'which ffmpeg' returned /usr/local/bin/ffmpeg.

**Comment by mdhiggins** [comment]
Hm, do you have those environment variables set or is that check incorrectly returning true

**Comment by mdhiggins** [comment]
Nevermind, I'm dumb. Fixed the issue

**Comment by player666au** [comment]
I think it is incorrectly returning true.

I have minimal vars set in docker-compose.yml, PGID, PUID, TZ. Nothing visible in config.xml.

Maybe they are set to null, and that existence returns true???

**Comment by player666au** [comment]
You did indeed fix it.

All good now, thank you
