### ISSUE TITLE
Latest version failure

### ISSUE THREAD

**Issue by TravisRoy** [mdhiggins/radarr-sma#48]
Pulled :latest today and now I'm getting the following error:

[Error] postRadarr.sh: Traceback (most recent call last): 
[Error] postRadarr.sh:   File "/usr/local/sma/postRadarr.py", line 10, in <module> 
[Error] postRadarr.sh:     from resources.mediaprocessor import MediaProcessor 
[Error] postRadarr.sh:   File "/usr/local/sma/resources/mediaprocessor.py", line 15, in <module> 
[Error] postRadarr.sh:     from autoprocess import plex 
[Error] postRadarr.sh:   File "/usr/local/sma/autoprocess/plex.py", line 5, in <module> 
[Error] postRadarr.sh:     from plexapi.myplex import MyPlexAccount 
[Error] postRadarr.sh: ModuleNotFoundError: No module named 'plexapi'

**Comment by mdhiggins** [comment]
Did you just pull SMA but not update the container? Plex API was added to the requirements and latest container should include it

**Comment by TravisRoy** [comment]
I recreated the entire container.

**Comment by mdhiggins** [comment]
Just did a fresh pull and it's working fine. Try that

**Comment by TravisRoy** [comment]
Working now.. not sure why.. 

But thanks for looking into it. :)
