### ISSUE TITLE
ffprobe/ffmpeg error

### ISSUE THREAD

**Issue by TravisRoy** [mdhiggins/radarr-sma#49]
When trying to do a convert I noticed this error in the log:

FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/bin/ffprobe'

When trying to run ffprobe from the command line, I get:

bash: /usr/local/bin/ffprobe: cannot execute: required file not found

But it is there:

-rwxr-xr-x 1 root users  133768 Mar 21 07:24 ffprobe

Same thing happens with ffmpeg. 

Installing with docker with the build tag.

**Comment by TravisRoy** [comment]
Docker compose below, digging into it more, might be due to the new base image being alpine and the ffmpeg tag uses is for ubuntu? Maybe?

  radarr:
    image: mdhiggins/radarr-sma:build
    container_name: radarr
    build:
      context: https://github.com/mdhiggins/radarr-sma.git#build
      args:
        ffmpeg_tag: 4.4-vaapi2004
    volumes:
      - /Docker/radarr-sma/opt/appdata/radarr:/config
      - /Docker/radarr-sma/opt/appdata/sma:/usr/local/sma/config
      - /media/merged/Media:/media/merged/Media/
      - /media/USB-1:/media/USB-1
      - /Docker/sabnzbd/downloads:/downloads
    ports:
      - 7879:7878
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - SMA_UPDATE=true
      - SMA_USE_REPO=true
      - SMA_HWACCEL=true
      - DOCKER_MODS=linuxserver/mods:universal-package-install
      - INSTALL_PACKAGES=libva-intel-driver|mesa-dri-gallium
    devices:
      - /dev/dri:/dev/dri

**Comment by TravisRoy** [comment]
Switching to latest rather than build, and removing the build section seems to have fixed it. 

Leaving this open just in case there's something else with the build tag

**Comment by mdhiggins** [comment]
I think this was an issue with permissions being set incorrectly during the migration to s6v3, which should be all sorted now
