### ISSUE TITLE
Mounting a file onto a directory

### ISSUE THREAD

**Issue by sgabe** [mdhiggins/radarr-sma#5]
This recent update broke the container, due to the fact the `VOLUME` instruction should be used to share directories.
https://github.com/mdhiggins/radarr-sma/blob/924358fb1ed83ca695d53ebb0fc7985d56501e6a/Dockerfile#L54
Starting the container fails with the following error message:
```
OCI runtime create failed: container_linux.go:346: starting container process caused \"process_linux.go:449: container init caused \\\"rootfs_linux.go:58: mounting \\\\\\\"/sharedfolders/Volumes/SMA/autoProcess.ini\\\\\\\" to rootfs \\\\\\\"/var/lib/docker/overlay2/e53e14f8365d4286fbb11fea920a1c05f32f09f7582e167738618d061f8c345e/merged\\\\\\\" at \\\\\\\"/var/lib/docker/overlay2/e53e14f8365d4286fbb11fea920a1c05f32f09f7582e167738618d061f8c345e/merged/usr/local/bin/sma/sickbeard_mp4_automator/autoProcess.ini\\\\\\\" caused \\\\\\\"not a directory\\\\\\\"\\\"\": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
```
I can confirm that `autoProcess.ini` has been replaced with a directory, causing the container to fail to start.
```console
root@radarr:/# ls -dl /usr/local/bin/sma/sickbeard_mp4_automator/autoProcess.ini
drwxr-xr-x 2 root root 4096 Feb 16 19:57 /usr/local/bin/sma/sickbeard_mp4_automator/autoProcess.ini
root@radarr:/#
```
I see that you have made the same with `sonarr-sma`, however, interestingly that container has survived the update. Anyway, I would recommend removing the affected `VOLUME` instruction.

**Comment by mdhiggins** [comment]
I shall fix this tonight, had to leave for work when I realized I had done this

**Comment by sgabe** [comment]
No problem, I have quickly rebuilt the image locally to prevent an outage in my movie theater. :wink:

**Comment by mdhiggins** [comment]
Should be resolved now

**Comment by sgabe** [comment]
Thank you for the quick fix.
