### ISSUE TITLE
FFMpeg cannot be found in the root directory!

### ISSUE THREAD

**Issue by Fritzh1** [mdhiggins/radarr-sma#50]
Hello,
I just installed FFMpegSharp but having a difficulty setting up the envirnoment.
Whenever i try to use the FFMpeg class, it shows an exception, "FFMpeg cannot be found in the root directory!".
I have copied FFMpeg.exe from the project's FFMpeg x64/x86 folders/and also tried latest executable from the official site on to c:\ffmpeg\bin and set <add key="ffmpegRoot" value="C:\ffmpeg\bin\" />.
I added the path to the Windows Environment variable, user variable, path.
I also tried using the project's FFMpeg x64/x86 folders in the config variable but all didn't work.
I am not sure what is wrong with my setting.
I looked for the answer in the web but nothing worked so far.
Could someone help me, please?
I am using Windows 11.
Thank you.

**Comment by mdhiggins** [comment]
You can't use a Windows binary file in a linux container, they are not cross compatible

**Comment by Fritzh1** [comment]
Hello mdhiggins,
Thank you for the comment. I am purely using Windows envirnment and I think I downloaded Windows executables.

**Comment by mdhiggins** [comment]
But the containers are linux based, so if you're going to override the included FFMPEG binaries that come with the container you'll need to provide linux binaries not windows ones

**Comment by Fritzh1** [comment]
I installed FFMpeg Nuget package that is Windows based.

**Comment by mdhiggins** [comment]
I feel like we're going in circles here. radarr-sma and any of the linuxserver based docker containers (also sonarr-sma) are not going to work with any windows FFMPEG binaries. 

Is there a reason the included binaries don't work for you? The containers don't need an outside source of FFMPEG

**Comment by Fritzh1** [comment]
sorry, i posted it at the wrong platform forum.


Best regards,

Fritz Hagi
MCSE, WSET Level 3
