### ISSUE TITLE
Error in update.py

### ISSUE THREAD

**Issue by RandomNinjaAtk** [mdhiggins/radarr-sma#8]
Log of error
```
[cont-init.d] 90-sma-config: executing...
From https://github.com/mdhiggins/sickbeard_mp4_automator
* branch master -> FETCH_HEAD
Already up to date.
Traceback (most recent call last):
File "/usr/local/sma/update.py", line 62, in <module>
main()
File "/usr/local/sma/update.py", line 25, in main
sslport = root.find("SslPort").text
AttributeError: 'NoneType' object has no attribute 'text'
[cont-init.d] 90-sma-config: exited 1.
```

I don't see the same error in sonarr.

Just a note, this is using the preview image tag

**Comment by mdhiggins** [comment]
Does your Radarr config not have SslPort in the XML file for some reason?

**Comment by mdhiggins** [comment]
Maybe they changed the config around in the preview. If you want post the whole config.xml

**Comment by mdhiggins** [comment]
Any updates on this? From what I can tell looking at Radarr's source code they didn't change this around

**Comment by RandomNinjaAtk** [comment]
Sorry I haven't gotten a chance to look at this. Been busy building a fresh container for SMA for sabnzbd. We can close this for now, because I may build my own container based on what I've learned for the other one.

**Comment by mdhiggins** [comment]
Well if you happen to be able to check what your config.xml looked like it would be helpful for debugging and isn't related to SAB at all (this error is related to reading the radarr config).

**Comment by RandomNinjaAtk** [comment]
@mdhiggins 
Just a note or possible design advice. I'm not sure why you bother reading those settings or attempting to update them in this docker.

Because everything is local, the IP should never change, the port should never change, SSL should never be needed. The only thing you actually have to read from the radarr config file is to get the API key to input into the SMA config file, because all the others can be set to the radarr default, no need to try to grab them from radarr's config.

This can also be applied to Sonarr...

Edit: This is still an issue that I haven't debugged yet, but probably using the information above, you could possibly resolve it that way, just a thought.

**Comment by mdhiggins** [comment]
Respectfully disagree. While its unlikely they would need to be changed from default they are user configurable from inside sonar/radarr and there's no reason they should be absent from the configuration file except for possibly with shifts to a new major release. Assuming users won't make changes to default options has never worked out well for me.

**Comment by mdhiggins** [comment]
```
<Config>
  <LogLevel>info</LogLevel>
  <BindAddress>*</BindAddress>
  <EnableSsl>False</EnableSsl>
  <SslCertPath></SslCertPath>
  <Port>7878</Port>
  <UrlBase></UrlBase>
  <ApiKey>ae732299732c4bfa92d8430f3fef4e8a</ApiKey>
  <AuthenticationMethod>None</AuthenticationMethod>
  <Branch>develop</Branch>
</Config>
```

That's the default Radarr v3 config. They've dropped the SslPort for a unified port it seems
